import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {
    setTimeout(() => {
      throw new Error("Not implemented")
    }, 5000);
  }, [])
  
  
  return (


    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       

       Hello 
       <button onClick={() =>  {throw new Error('Error occurred in MyComponent.')}}>Click</button>
      </main>
    </>
  )
}
